import re
import unicodedata


def sanitize_text(text: str) -> str:
    """Normalize text for reliable export while preserving normal punctuation."""
    text = unicodedata.normalize("NFKC", text or "")
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u00a0": " ",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def split_terms(terms: str) -> list[str]:
    return [part.strip() for part in terms.split(";") if part.strip()]


def demo_document(document_type: str, parties: str, terms: str, effective_date: str, jurisdiction: str) -> str:
    clauses = split_terms(terms)
    clause_text = "\n".join(f"{i}. {item}" for i, item in enumerate(clauses, 1))
    return f"""LEGAL DOCUMENT DRAFT

{document_type.upper()}

Effective Date: {effective_date}
Jurisdiction: {jurisdiction}

PARTIES
{parties}

PURPOSE
This is a demonstration draft generated by LegalEase in DEMO_MODE. Replace all placeholders and have the document reviewed for the applicable jurisdiction before use.

TERMS AND CONDITIONS
{clause_text or "1. [TERMS TO BE COMPLETED]"}

GENERAL PROVISIONS
1. Entire Agreement. This document records the terms supplied by the parties and should be reviewed before execution.
2. Amendments. Any amendment should be made in writing and approved by the parties.
3. Governing Law. [JURISDICTION TO BE CONFIRMED].

SIGNATURES

Party 1: ______________________________
Name: _________________________________
Date: __________________________________

Party 2: ______________________________
Name: _________________________________
Date: __________________________________

DISCLAIMER
This document is an AI-generated draft for informational and document-preparation purposes and is not a substitute for advice from a qualified legal professional.
"""
